### ISSUE TITLE
phono3py-mode-plot error

### ISSUE THREAD

**Issue by baolong-jiji** [skelton-group/Phono3py-Tools#1]
Dear administers,
The Phono3py-Power-Tools is a vary wondeful job,when iI run phono3py-mode there is an error.The errors as follows:
Traceback (most recent call last):
  File "/home/jbl/Phono3py-Power-Tools/phono3py-mode-plot", line 458, in <module>
    plot_y = _GetDataFuncLUT[args.PlotY](kappa_hdf5, args.Temperature, args.UseRTA).ravel()
  File "/home/jbl/Phono3py-Power-Tools/phono3py-mode-plot", line 72, in <lambda>
    'kappa' : lambda f, t, rta : f.GetModeKappaAve(t, lbte_rta = rta),
  File "/home/jbl/Phono3py-Power-Tools/Phono3pyPowerTools/Phono3pyIO.py", line 297, in GetModeKappaAve
    mode_kappa[t_index, :, :, :3], axis = -1
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/jbl/miniconda3/lib/python3.9/site-packages/h5py/_hl/dataset.py", line 752, in __getitem__
    selection = sel.select(self.shape, args, dataset=self)
  File "/home/jbl/miniconda3/lib/python3.9/site-packages/h5py/_hl/selections.py", line 82, in select
    return selector.make_selection(args)
  File "h5py/_selector.pyx", line 272, in h5py._selector.Selector.make_selection
  File "h5py/_selector.pyx", line 181, in h5py._selector.Selector.apply_args
TypeError: Only 1D arrays allowed for fancy indexing

I would be appreciated if you could help me saolve this problem.
best wishes!
baolong ji

**Comment by JMSkelton** [comment]
Hi Baolong Ji,

This bug was caused by an incompatibility between the return value of np.argwhere() and newer versions of H5py.

It should now be fixed - please update your Phono3py-Power-Tools installation, check whether phono3py-mode-plot now works as expected, and re-open the issue if you have any further problems.

Best wishes,

Jonathan
